instaMeter/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@publicHomePage');
Route::get('/profile', 'UserController@index');
Route::get('/friends', 'UserController@show');
Route::get('/myProfile', 'UserController@myProfileInfo');

Auth::routes();

Route::resource('posts','PostController');

Route::resource('comments','CommentController');

Route::resource('users','UserController');

instaMeter/resources/views/adminPanel/create.blade.php
@extends('layouts.template')

@section('title','Add New Post')

@section('content')
<style type="text/css">
.uploader {
  position:relative; 
  overflow:hidden; 
  width:300px; 
  height:350px;
  background:#f3f3f3; 
  border:2px dashed #e8e8e8;
}

#filePhoto{
  position:absolute;
  width:300px;
  height:400px;
  top:-50px;
  left:0;
  z-index:2;
  opacity:0;
  cursor:pointer;
}

.uploader img{
  position:absolute;
  width:302px;
  height:352px;
  top:-1px;
  left:-1px;
  z-index:1;
  border:none;
}
</style>

<h1>Add New Post</h1>

<div class="col-sm-8 col-sm-offset-2">
  <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
  {{ csrf_field() }}
    <div class="form-group"><br><br>

      <div class="uploader" onclick="$('#filePhoto').click()">
        <br><br>click here or drag here your images for preview 
        <img src=""/>
        <input type="file" name="image"  id="filePhoto" required="required" />
      </div>

      <br><br><label>Add Title</label>
      <br><textarea name="title" style="height:60px; width:250px" required="required"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">POST</button>
    <a href="../posts" class="btn btn-default pull-right">Go Back</a>
  </form>
</div>


<script type="text/javascript">
var imageLoader = document.getElementById('filePhoto');
  var imageName = document.getElementById('filePhoto');
  
imageLoader.addEventListener('change', handleImage, false);

function handleImage(e) {
  img = imageName.value;
  ext = img.substr((img.lastIndexOf('.') + 1));

  if (ext == 'png' || ext == 'jpg' || ext == 'jpeg' || ext == 'PNG' || ext == 'JPG' || ext == 'JPEG'){
    var reader = new FileReader();
    reader.onload = function (event) {
        $('.uploader img').attr('src',event.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);        
  }

  else {
    imageName.value = null;
    alert("Extension not available");
  }
}
</script>
@endsection

instaMeter/resources/views/adminPanel/friends.blade.php
  @extends('layouts.viewPostTemplate')

@section('title', 'View Post')

@section('content')

<div class="row">
	<br><a href="{{ url('/') }}" class="btn btn-primary">Go Back</a>
</div>

<div align="center">
<?php 
	for($i=0;$i<count($data);$i++) {
?>	    
  <div class="well well-lg" style="width:400px">
    <p align="left"><img src="../../storage/app/<?php echo $data[$i]->image; ?>" alt="user pic" width="50" height="50"><strong>&nbsp&nbsp&nbsp&nbsp<?php echo ($data[$i]->name); ?></strong></p>

    <form action="{{ route('users.update', $data[$i]->id) }}" method="post">
      {{ csrf_field() }}
      <input type="hidden" name="_method" value="PUT">
    	<button type="submit" name="follow" class="btn btn-info pull-right" style="background-color:green" <?php echo $p ;?>>FOLLOW</button>
    </form>
    <br>
  </div>
	<?php 
		}
	?>
	
</div>
@endsection

instaMeter/resources/views/adminPanel/home.blade.php
@extends('layouts.template')

@section('title','Admin Panel')

@section('content')

<div class="loginBox nav navbar-nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li>
        <a href="myProfile">My Profile</a>
        <a href="profile">Profile</a>
        <a href="logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
        
        <form id="logout-form" action="logout" method="POST" style="display: none;"> {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </li>
</div>

<h1>Admin Panel</h1>
<br><a href="{{ url('/') }}" class="btn btn-primary pull-left">Go Back</a>

<a href="posts/create" class="btn btn-primary pull-right">Add New Post</a>
<br><br><br>
<table class="table">
  <thead>
    <th>ID</th>
    <th>Image</th>
    <th>Title</th>
    <th>Delete</th>
  </thead>

  <tbody>
    @foreach($posts as $post)
    <tr>
      <th>{{ $post-> id }}</th>
      <td><img src="../storage/app/{{ $post->image }}" alt="user pic" width="100" height="100" /></td>
      <td>{{ $post-> title }}</td>
      <td>
      <form action="{{ route('posts.destroy', ['id'=>$post->id]) }}" method="post">
      {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE">

        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>

@endsection

instaMeter/resources/views/adminPanel/index.blade.php
@extends('layouts.publicHomePageTemplate')

@section('title', 'MandM InstaMeter')

@section('content')

<div align="center">
  <h2>Most Recent Posts</h2>
  @foreach($posts as $post)
    <a href="{{ route('posts.show', ['id'=>$post->id]) }}">
    <img src="../storage/app/{{ $post->image }}" alt="user pic" width="300" height="300"></a>
    <p>LIKES: {{ $post->likes }} &nbsp&nbsp&nbsp COMMENTS: {{ $post->comments }}</p>

    <form action="{{ route('posts.update', ['id'=>$post->id]) }}" method="post">
    {{ csrf_field() }}
      <input type="hidden" name="_method" value="PUT">
      <button type="submit" name="like" class="btn btn-info">LIKE</button>
    </form>

    <form action="{{ route('comments.update', ['id'=>$post->id]) }}" method="post">
    {{ csrf_field() }}
      <input type="hidden" name="_method" value="PUT">

      <br><br><textarea name="commentText" style="height:60px; width:250px" required="required"></textarea>
      <br><button type="submit" name="comment" class="btn btn-info">COMMENT</button>
      <br><br>
    </form>
      @endforeach

</div>

@endsection

instaMeter/resources/views/adminPanel/myProfileInfo.blade.php
@extends('layouts.publicHomePageTemplate')

@section('title','Admin Panel')

@section('content')


@if (Auth::guest())

<div>
  <img src="wall.jpg" alt="nooo" width="100%" height="500">
</div>

@else
<div align="center">
  <h2>My Profile</h2>

  @if($posts)
  @foreach($posts as $post)
  <a href="{{ route('posts.show', ['id'=>$post->id]) }}">
  <img src="../storage/app/{{ $post->image }}" alt="user pic" width="300" height="300"></a>
  <p><strong>TITLE: {{ $post->title }} </strong></p>
  <p>LIKES: {{ $post->likes }} &nbsp&nbsp&nbsp COMMENTS: {{ $post->comments }}</p>

  <form action="{{ route('posts.update', ['id'=>$post->id]) }}" method="post">
  {{ csrf_field() }}
    <input type="hidden" name="_method" value="PUT">
    
    <button type="submit" name="<?php foreach ($isLiked as $dis) { if ($dis->post_id == $post->id) { echo 'un';}}?>like" class="btn btn-info"><?php foreach ($isLiked as $dis) { if ($dis->post_id == $post->id) { echo 'UN';}}?>LIKE</button> 

  </form>

  <form action="{{ route('comments.update', ['id'=>$post->id]) }}" method="post">
  {{ csrf_field() }}
    <input type="hidden" name="_method" value="PUT">

    <br><br><textarea name="commentText" style="height:60px; width:250px" required="required"></textarea>
    <br><button type="submit" name="comment" class="btn btn-info">COMMENT</button>
    <br><br>
  </form>
    @endforeach
@endif
 @endif
</div>

@endsection

instaMeter/resources/views/adminPanel/profile.blade.php
@extends('layouts.template')

@section('title','Admin Panel')

@section('content')

<div class="loginBox nav navbar-nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li>
        <a href="myProfile">My Profile</a>
        <a href="profile">Profile</a>
        <a href="logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

        <form id="logout-form" action="logout" method="POST" style="display: none;"> {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </li>
</div>

<h1>Admin Profile</h1>
<br><a href="posts" class="btn btn-primary pull-left">Go Back</a>

<a href="posts/create" class="btn btn-primary pull-right">Add New Post</a>
<br><br><br>



<div class="col-sm-8 col-sm-offset-2">
  <img src="../storage/app/{{ $id }}" alt="user pic" width="250" height="250" />

  <form action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
  {{ csrf_field() }}
    <div class="form-group"><br><br>
      <label for="title">Change Image:</label><br>
      <br><input type="file" name="image" required="required">
    </div>

    <br><br><button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>

@endsection