myblog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('blog/home');
//});

Route::get('/', 'PostController@publicHomePage');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('posts','PostController');

myblog/app/Post.php
<?php

namespace myblog;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

myblog/app/User.php
<?php

namespace myblog;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

myblog/app/Http/Controllers/Controller.php
<?php

namespace myblog\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

myblog/app/Http/Controllers/HomeController.php
<?php

namespace myblog\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

myblog/app/Http/Controllers/PostController.php
<?php

namespace myblog\Http\Controllers;

use myblog\Post;
use Illuminate\Http\Request;
use Auth;

class PostController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */


  public function publicHomePage()
  {
    $posts = Post::paginate(5);
    return view('blog/home', ['posts'=>$posts]);
  }
  
  public function index()
  {
    $loggedUserId = Auth::id();
    $posts = Post::all()->where('user_id', $loggedUserId);
    return view('adminPanel/home', ['posts'=>$posts]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('adminPanel/create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $post = new Post;
    $postTitle = $request->title;
    $postBody = $request->body;
    $postUserId = Auth::id();

    $post->user_id = $postUserId;
    $post->title = $postTitle;
    $post->body = $postBody;

    $post->save();

    return redirect()->route('posts.index');
  }

  /**
   * Display the specified resource.
   *
   * @param  \myblog\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    $post = Post::find($id);
    $data = array(
        'id' => $id,
        'post' => $post
    );

    return view('blog.view_post', $data);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \myblog\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $post = Post::find($id);

    return view('adminPanel.edit', ['post'=>$post]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \myblog\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $post = Post::find($id);
    $post->title = $request->title;
    $post->body = $request->body;

    $post->save();

    return redirect()->route('posts.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \myblog\Post  $post
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $post = Post::find($id);
    $post->delete();
    return redirect()->route('posts.index');
  }
}

myblog/app/Http/Controllers/Wohoo.php
<?php

namespace myblog\Http\Controllers;

use Illuminate\Http\Request;
use myblog\Http\Requests;

class Wohoo extends Controller
{
    /**
    *
    *@return Response
    */
    public function index()
    {
    	$users = DB::table('users')->get();

        return view('user.index', ['users' => $users]);
    }
}

myblog/resources/views/adminPanel/create.blade.php
@extends('layouts.template')

@section('title','Add New Post')

@section('content')
<h1>Add New Post</h1>

<div class="col-sm-8 col-sm-offset-2">
  <form action="{{ route('posts.store') }}" method="post">
  {{ csrf_field() }}
    <div class="form-group">
      <label for="title">Title:</label>
      <input type="text" name="title" class="form-control" required="required">
    </div>

    <div class="form-group">
      <label for="body">Body:</label>
      <textarea name="body" class="form-control" cols="30" rows="10" required="required"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="../posts" class="btn btn-default pull-right">Go Back</a>
  </form>
</div>

@endsection

myblog/resources/views/adminPanel/edit.blade.php
@extends('layouts.template')

@section('title','Edit Post #' . $post->id)

@section('content')
<h1>Edit Post # {{ $post->id }}</h1>

<div class="col-sm-8 col-sm-offset-2">
  <form action="{{ route('posts.update', ['id'=>$post->id]) }}" method="post">
  {{ csrf_field() }}

    <input type="hidden" name="_method" value="PUT">
    <div class="form-group">
      <label for="title">Title:</label>
      <input type="text" name="title" class="form-control" value="{{ $post->title }}" required="required">
    </div>

    <div class="form-group">
      <label for="body">Body:</label>
      <textarea name="body" class="form-control" cols="30" rows="10" required="required">{{ $post->body }}</textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="../" class="btn btn-default pull-right">Go Back</a>
  </form>
</div>

@endsection

myblog/resources/views/adminPanel/home.blade.php
@extends('layouts.template')

@section('title','Blog Admin Panel')

@section('content')

<div class="loginBox nav navbar-nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li>
        <a href="logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

        <form id="logout-form" action="logout" method="POST" style="display: none;"> {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </li>
</div>

<h1>Admin Panel</h1>
<a href="{{ url('/') }}" class="btn btn-primary pull-left">Go Back</a>

<a href="posts/create" class="btn btn-primary pull-right">Add New Blog Post</a>
<br><br><br>
<table class="table">
  <thead>
    <th>id</th>
    <th>title</th>
    <th>body</th>
    <th>edit</th>
    <th>delete</th>
  </thead>

  <tbody>
    @foreach($posts as $post)
    <tr>
      <th>{{ $post-> id }}</th>
      <td>{{ $post-> title }}</td>
      <td>{{ $post-> body }}</td>
      <td><a href="{{ route('posts.edit', ['id'=>$post->id]) }}" class="btn btn-info">Edit</a></td>
      <td>
      <form action="{{ route('posts.destroy', ['id'=>$post->id]) }}" method="post">
      {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE">

        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>

@endsection

myblog/resources/views/blog/home.blade.php
@extends('layouts.publicHomePageTemplate')

@section('title', 'Blog Public Home Page')

@section('content')

  <div>
    <h2>Top 10 Most Recent Posts</h2>
    @foreach($posts as $post)
    <div class="well well-lg">
      <h3>{{ $post->title }}</h3>
      <p>{{ $post->body }}</p>
      <a href="{{ route('posts.show', ['id'=>$post->id]) }}" class="btn btn-default pull-right">View Post</a>
      &nbsp;
    </div>
    @endforeach

    <div class="row text-center">
      {{ $posts->links() }}
    </div>
  </div>

@endsection

myblog/resources/views/blog/view_post.blade.php
@extends('layouts.viewPostTemplate')

@section('title', 'View Post #'. $id)

@section('content')
	<br><br>
	<h1>{{ $post->title }}</h1>
	<br><br>
	<p>{{ $post->body}}</p>
	<br><br>

	<div class="row" align="center">
		<br><a href="{{ url('/') }}" class="btn btn-primary">Go Back</a>
	</div>

@endsection